### ISSUE TITLE
Longer fields for text boxes please

### ISSUE THREAD

**Issue by YanceySlide** [Xen0ph0n/NinjaJobs#11]
My job descriptions tend to be intentionally wordy so as to not be boring and dry to read.  Would it be possible to up the limits on the "Full Position Description" and "Desired Skills and Experience" fields?  They're at 2000/1000 now.  Could they both be doubled?

**Comment by Xen0ph0n** [comment]
Changed both to 4000 chars as well as the place for a resume when applying up to 4000. I'll add pdf/word attachment shortly. Thanks!
