### ISSUE TITLE
Delete Job Code from the Application

### ISSUE THREAD

**Issue by deeso** [Xen0ph0n/NinjaJobs#12]
Remove the NINJA08 code from the allowed job codes in the application.  Going forward you may want to scrub your screenshots before uploading them to GH.   Here is the image with the info in it: https://github.com/Xen0ph0n/NinjaJobs/issues/8

![image](https://cloud.githubusercontent.com/assets/1205295/7261359/bb4f01bc-e836-11e4-889a-3fb31d207ffc.png)

Cool idea, but don't know if I should be trusted ;)

**Comment by Xen0ph0n** [comment]
Haha good call, luckily it'll just let you apply to my posting :) thanks.

**Comment by deeso** [comment]
I think I could apply to any posting.  I did not try though.  I helped
ph3n0 set up an account so he could apply to another job.

**Comment by ph3n0** [comment]
Ha,  not sure if it went through,  but it did send me a survey.  Tried to ping you on LinkedIn but their messaging system was down. Go figure!  :D
