### ISSUE TITLE
Allow sort jobs by X

### ISSUE THREAD

**Issue by b3nw** [Xen0ph0n/NinjaJobs#4]
X being things like:
- Location
- Travel
- Comp
- etc

**Comment by Xen0ph0n** [comment]
Closed previous feature request https://github.com/Xen0ph0n/NinjaJobs/issues/1 as you phrased it better. 

Will add this, it shouldn't be too hard. Currently sorts by date decending, so I'd just need to replace with a variable .. and feed it by a button on the page, ...might screw with pagination but I don't think so. I'm thinking some buttons across the top indicative of the sort desired. Nothing fancy as I don't think there will be that many jobs. 

I could probably raise the jobs per page to 20 or so (or make it variable as well) to help with user experience browsing.

**Comment by Xen0ph0n** [comment]
![screen shot 2013-10-28 at 3 26 07 pm](https://f.cloud.github.com/assets/2313682/1423175/d640419a-4006-11e3-997c-762e62c00a9c.png)

Sort by variables and swap up ascending/descending
