### ISSUE TITLE
Add Ability to reset password

### ISSUE THREAD

**Issue by stephanchenette** [Xen0ph0n/NinjaJobs#9]
The most common and secure way to reset a password is to allow the user to click a reset button link. Then next step is that they would enter the username/email address they want to reset. This would cause the backend system to generate a unique code and send an email to your registered account with a link that uses this code as a query parameter. This code should be large enough so it can't be reasonable brute forced, and is not tied to the username or the time on the system. use a secure rand function. If you need help I'd be happy to suggest how to do this. The user's account password is not reset until the registered user clicks on the link and is sent to a reset password page where they are asked to reset their password, one field for password, one for verification password. Upon clicking reset, the user's password is then reset and they are redirected to the login page.
e.g.
https://login.skype.com/account/password-reset-request

this resource also might be helpful:
http://www.troyhunt.com/2012/05/everything-you-ever-wanted-to-know.html

**Comment by Xen0ph0n** [comment]
Agree 100% this is critical, will examine how best to implement, Thanks!

**Comment by Xen0ph0n** [comment]
All done, "it's dangerous" is a pretty awesome library for python. 

Scratch built but a lot of help from this great gist: http://flask.pocoo.org/snippets/50/

https://ninjajobs.org/reset/

1) Enter username
2) Crypto hash link is sent to registered email address
3) click on hash and enter new password 
4) Profit!
